import { addIcons } from 'ionicons';
import {
  add,
  addCircleOutline,
  barChartOutline,
  busOutline,
  cartOutline,
  cashOutline,
  close,
  closeOutline,
  createOutline,
  documentTextOutline,
  eyeOutline,
  gridOutline,
  helpCircleOutline,
  homeOutline,
  logOutOutline,
  medkitOutline,
  notificationsOutline,
  personCircleOutline,
  pieChartOutline,
  pricetagOutline,
  pricetagsOutline,
  removeCircleOutline,
  schoolOutline,
  settingsOutline,
  trash,
  trashOutline,
  trendingDown,
  trendingUp,
  tvOutline,
  walletOutline,
} from 'ionicons/icons';

/** Iconos usados en la app (bundle local, sin CDN — requerido en Capacitor). */
export function registerAppIcons(): void {
  addIcons({
    add,
    'add-circle-outline': addCircleOutline,
    'bar-chart-outline': barChartOutline,
    'bus-outline': busOutline,
    'cart-outline': cartOutline,
    'cash-outline': cashOutline,
    close,
    'close-outline': closeOutline,
    'create-outline': createOutline,
    'document-text-outline': documentTextOutline,
    'eye-outline': eyeOutline,
    'grid-outline': gridOutline,
    'help-circle-outline': helpCircleOutline,
    'home-outline': homeOutline,
    'log-out-outline': logOutOutline,
    'medkit-outline': medkitOutline,
    'notifications-outline': notificationsOutline,
    'person-circle-outline': personCircleOutline,
    'pie-chart-outline': pieChartOutline,
    'pricetag-outline': pricetagOutline,
    'pricetags-outline': pricetagsOutline,
    'remove-circle-outline': removeCircleOutline,
    'school-outline': schoolOutline,
    'settings-outline': settingsOutline,
    trash,
    'trash-outline': trashOutline,
    'trending-down': trendingDown,
    'trending-up': trendingUp,
    'tv-outline': tvOutline,
    'wallet-outline': walletOutline,
  });
}
