import { addIcons } from 'ionicons';
import {
  add,
  addCircleOutline,
  arrowBackOutline,
  barChartOutline,
  busOutline,
  cartOutline,
  cashOutline,
  chevronBackOutline,
  chevronForwardOutline,
  close,
  closeOutline,
  createOutline,
  documentTextOutline,
  eyeOutline,
  gridOutline,
  helpCircleOutline,
  homeOutline,
  logOutOutline,
  medkitOutline,
  notificationsOutline,
  personCircleOutline,
  pieChartOutline,
  pricetagOutline,
  pricetagsOutline,
  removeCircleOutline,
  schoolOutline,
  settingsOutline,
  trash,
  trashOutline,
  trendingDown,
  trendingUp,
  tvOutline,
  walletOutline,
  receiptOutline,
  calculatorOutline,
  statsChartOutline,
  basketOutline,
  bagOutline,
  storefrontOutline,
  ticketOutline,
  bedOutline,
  constructOutline,
  hammerOutline,
  bulbOutline,
  carOutline,
  carSportOutline,
  subwayOutline,
  trainOutline,
  boatOutline,
  bicycleOutline,
  airplaneOutline,
  restaurantOutline,
  cafeOutline,
  pizzaOutline,
  wineOutline,
  iceCreamOutline,
  fastFoodOutline,
  nutritionOutline,
  heartOutline,
  pulseOutline,
  bandageOutline,
  fitnessOutline,
  bagHandleOutline,
  bookOutline,
  libraryOutline,
  readerOutline,
  journalOutline,
  laptopOutline,
  desktopOutline,
  phonePortraitOutline,
  phoneLandscapeOutline,
  hardwareChipOutline,
  wifiOutline,
  gameControllerOutline,
  musicalNoteOutline,
  musicalNotesOutline,
  cameraOutline,
  videocamOutline,
  filmOutline,
  imageOutline,
  briefcaseOutline,
  businessOutline,
  clipboardOutline,
  flashOutline,
  waterOutline,
  pawOutline,
  giftOutline,
  starOutline,
  archiveOutline,
  ribbonOutline,
  peopleOutline,
  peopleCircleOutline,
  personOutline,
  personAddOutline,
  personRemoveOutline,
  mapOutline,
  navigateOutline,
  locationOutline,
  compassOutline,
  bookmarkOutline,
  saveOutline,
  refreshOutline,
  reloadOutline,
  infiniteOutline,
} from 'ionicons/icons';

/**
 * Iconos usados en la app (bundle local, sin CDN)
 */
export function registerAppIcons(): void {
  addIcons({
    add,
    'add-circle-outline': addCircleOutline,
    'arrow-back-outline': arrowBackOutline,
    'bar-chart-outline': barChartOutline,
    'bus-outline': busOutline,
    'cart-outline': cartOutline,
    'cash-outline': cashOutline,
    'chevron-back-outline': chevronBackOutline,
    'chevron-forward-outline': chevronForwardOutline,
    close,
    'close-outline': closeOutline,
    'create-outline': createOutline,
    'document-text-outline': documentTextOutline,
    'eye-outline': eyeOutline,
    'grid-outline': gridOutline,
    'help-circle-outline': helpCircleOutline,
    'home-outline': homeOutline,
    'log-out-outline': logOutOutline,
    'medkit-outline': medkitOutline,
    'notifications-outline': notificationsOutline,
    'person-circle-outline': personCircleOutline,
    'pie-chart-outline': pieChartOutline,
    'pricetag-outline': pricetagOutline,
    'pricetags-outline': pricetagsOutline,
    'remove-circle-outline': removeCircleOutline,
    'school-outline': schoolOutline,
    'settings-outline': settingsOutline,
    trash,
    'trash-outline': trashOutline,
    'tv-outline': tvOutline,
    'wallet-outline': walletOutline,
    'receipt-outline': receiptOutline,
    'calculator-outline': calculatorOutline,
    'stats-chart-outline': statsChartOutline,
    'basket-outline': basketOutline,
    'bag-outline': bagOutline,
    'bag-handle-outline': bagHandleOutline,
    'storefront-outline': storefrontOutline,
    'ticket-outline': ticketOutline,
    'bed-outline': bedOutline,
    'construct-outline': constructOutline,
    'hammer-outline': hammerOutline,
    'bulb-outline': bulbOutline,
    'car-outline': carOutline,
    'car-sport-outline': carSportOutline,
    'subway-outline': subwayOutline,
    'train-outline': trainOutline,
    'boat-outline': boatOutline,
    'bicycle-outline': bicycleOutline,
    'airplane-outline': airplaneOutline,
    'restaurant-outline': restaurantOutline,
    'cafe-outline': cafeOutline,
    'pizza-outline': pizzaOutline,
    'wine-outline': wineOutline,
    'ice-cream-outline': iceCreamOutline,
    'fast-food-outline': fastFoodOutline,
    'nutrition-outline': nutritionOutline,
    'heart-outline': heartOutline,
    'pulse-outline': pulseOutline,
    'bandage-outline': bandageOutline,
    'fitness-outline': fitnessOutline,
    'book-outline': bookOutline,
    'library-outline': libraryOutline,
    'reader-outline': readerOutline,
    'journal-outline': journalOutline,
    'laptop-outline': laptopOutline,
    'desktop-outline': desktopOutline,
    'phone-portrait-outline': phonePortraitOutline,
    'phone-landscape-outline': phoneLandscapeOutline,
    'hardware-chip-outline': hardwareChipOutline,
    'wifi-outline': wifiOutline,
    'game-controller-outline': gameControllerOutline,
    'musical-note-outline': musicalNoteOutline,
    'musical-notes-outline': musicalNotesOutline,
    'camera-outline': cameraOutline,
    'videocam-outline': videocamOutline,
    'film-outline': filmOutline,
    'image-outline': imageOutline,
    'briefcase-outline': briefcaseOutline,
    'business-outline': businessOutline,
    'clipboard-outline': clipboardOutline,
    'flash-outline': flashOutline,
    'water-outline': waterOutline,
    'paw-outline': pawOutline,
    'gift-outline': giftOutline,
    'star-outline': starOutline,
    'archive-outline': archiveOutline,
    'ribbon-outline': ribbonOutline,
    'people-outline': peopleOutline,
    'people-circle-outline': peopleCircleOutline,
    'person-outline': personOutline,
    'person-add-outline': personAddOutline,
    'person-remove-outline': personRemoveOutline,
    'map-outline': mapOutline,
    'navigate-outline': navigateOutline,
    'location-outline': locationOutline,
    'compass-outline': compassOutline,
    'bookmark-outline': bookmarkOutline,
    'save-outline': saveOutline,
    'refresh-outline': refreshOutline,
    'reload-outline': reloadOutline,
    'infinite-outline': infiniteOutline,
    'trending-down-outline': trendingDown,
    'trending-up-outline': trendingUp,
  });
}